### ISSUE TITLE
Have the Page Load Up a Sample Project by Default

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/design_explorer_lite#18]
... just like the full [Design Explorer](https://tt-acm.github.io/DesignExplorer/)

@MingboPeng , what do you think of this?  I feel that it will make the page a lot more inviting than the blank page that it is currently.

I can clean up the sample project in the resources folder if you agree it's a good idea.

**Comment by MingboPeng** [comment]
@chriswmackey  makes sense. We can also use the current example file form DesignExplorer.

**Comment by theo-armour** [comment]
@chriswmackey @MingboPeng 

I have been following the progress of this project closely and very much look forward to seeing a demo in operation.

Given that I d not have Rhino/Dynamo Grashopper/Honeybee, this could en up being the first Ladybug Tools app that I can actually use (apart from those in a certain arachnid repo ;-)
 
Other useful things you might consider adding:

* Links to the original Design Explorer and it details
* A read me that describes that this is all about and how to us it
   * A screen capture in the red me is always helpful

Congratulations on a nice start. Fingers crossed all the efforts finish off nicely and quickly.

**Comment by chriswmackey** [comment]
I just added a default sample project today, which should hopefully make it clearer what the purpose of the tool is,  @theo-armour .

Documentation is the next item on my agenda and you can expect to see the wiki filling up over the next few days along with some links on the page itself.

I suggest keeping an eye there as well as on the other github issues related to documentation if you are looking to start playing around with it.
