### ISSUE TITLE
add the static link ability

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/design_explorer_lite#8]

**Comment by chriswmackey** [comment]
This is the only major thing that is stopping me from using this on every project now that all major bugs are fixed and the page layout and styling is working much better.

While all the other features in the issue page would be really nice, I think it may be worth prioritizing this one.

**Comment by MingboPeng** [comment]
Agreed. but we have used in one of our project already. I made an instruction pdf for client showing how to use it :>  
But totally agreed, this should be added first.

**Comment by chriswmackey** [comment]
Hah!  You are already one step ahead of me, then.
And that's quite a good client that you have there

I have enough trouble getting people to follow an even simpler instruction:
"Don't use internet explorer"

**Comment by paul42** [comment]
it's very possible to get access to the current URL - if you make links like /etc/{{GOOGLE ID}} you can get that when the page loads: https://stackoverflow.com/questions/406192/get-current-url-in-javascript

**Comment by chriswmackey** [comment]
I see that this has largely been addressed.  Thanks @MingboPeng !
Feel free to close out the issue whenever you think it's appropriate.
